version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - experio-net
  
  admin-dashboard:
    build:
      context: .
      dockerfile: dockerfile_admin
    container_name: admin-dashboard
    command: uvicorn main:app --host 0.0.0.0 --port 8004
    ports:
      - "8004:8004"
    env_file:
      - ../.env
    networks:
      - experio-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - experio-net

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - experio-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana-dashboards-provider.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    networks:
      - experio-net

networks:
  experio-net:
    name: experio-net
    driver: bridge
